version: "3.5"

services:
  web:
    container_name: web
    hostname: web
    image: osmtw/osm-tiles:latest
    depends_on:
      - postgis
    ports:
      - 8080:80
    environment:
      - PG_ENV_POSTGRES_DB=gis
      - PG_ENV_POSTGRES_USER=postgres
      - PG_ENV_POSTGRES_PASSWORD=postgres
      - PG_PORT_5432_TCP_ADDR=postgis
      - PG_PORT_5432_TCP_PORT=5432
    # once every tile is rendered, you can tell mod_tile that everything is OK:
    # touch /var/lib/mod_tile/planet-import-complete

  postgis:
    container_name: postgis
    hostname: postgis
    image: mdillon/postgis:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
    volumes:
      - ./data:/var/lib/postgresql

  osm2pgsql:
    container_name: osm2pgsql
    hostname: osm2pgsql
    image: osmtw/osm2pgsql
    depends_on:
      - postgis
    environment:
      - PG_ENV_POSTGRES_DB=gis
      - PG_ENV_POSTGRES_USER=postgres
      - PG_ENV_POSTGRES_PASSWORD=postgres
      - PG_PORT_5432_TCP_ADDR=postgis
      - PG_PORT_5432_TCP_PORT=5432
    volumes:
      - ./osm:/osm
      - ./osm-extract:/osm-extract
    command: osm2pgsql -c --cache 2000 -G -H postgis -U postgres -d gis --number-processes 4 /osm-extract/reunion-latest.osm.pbf
    # Help !?
    # command: osm2pgsql -h -v
    # -E|--proj num    Use projection EPSG:num.
    # -G|--multi-geometry  Generate multi-geometry features in postgresql tables.
    # --number-processes   Specifies the number of parallel processes
    #                      used for certain operations (default is 1).
    # -s|--slim  Store temporary data in the database. This greatly
    #            reduces the RAM usage but is much slower. This switch is
    #            required if you want to update with --append later.
    # -S|--style       Location of the style file. Defaults to
    #                 /usr/local/share/osm2pgsql/default.style.
